import type { CmsDatabase } from "./types";
import { programs } from "@/lib/data/programs";
import {
  projects,
  events,
  newsArticles,
  galleryItems,
  opportunities,
  resources,
} from "@/lib/data/content";
import {
  nationalStats,
  districts,
  testimonials,
  partners,
  nationalLeaders,
  coreValues,
} from "@/lib/data/stats";

export function createSeedDatabase(): CmsDatabase {
  return {
    site: {
      orgName: "Patriotic Youths of Uganda",
      tagline: "Building Uganda Through Unity, Service, Leadership, and Development.",
      heroHeadline: "Building Uganda Through Unity, Service, Leadership & Development",
      heroSubheadline:
        "Join the movement shaping Uganda's future. Across all 146 districts, young patriots are leading change through service, innovation, and national pride.",
      supportEmail: "info@pyu.ug",
      hotline: "+256 700 000 000",
      whatsapp: "+256 700 000 000",
      whatsappGroup: "https://chat.whatsapp.com/H7GOLHTLRYQ5IPSomBEu52",
      whatsappGroupLabel: "Join Our Official WhatsApp Group",
      whatsappGroupDescription:
        "Connect with patriots nationwide — get event alerts, opportunities, and real-time updates. Join the official PYU WhatsApp community now.",
      address: "Plot 1, Parliamentary Avenue, Kampala, Uganda",
      facebook: "https://facebook.com",
      twitter: "https://x.com",
      instagram: "https://instagram.com",
      linkedin: "https://linkedin.com",
      youtube: "https://youtube.com",
      tiktok: "https://tiktok.com",
      logoUrl: "",
      heroImage:
        "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80",
      ogImage: "/og-image.png",
      maintenanceMode: false,
      primaryColor: "#059669",
      secondaryColor: "#fcdc04",
      accentColor: "#d90000",
      ctaTitle: "Ready to Build Uganda's Future?",
      ctaDescription:
        "Whether you join as a member, volunteer your time, or support our mission financially — every contribution counts.",
      aboutVision:
        "A united, prosperous Uganda led by patriotic, skilled, and ethical young people who champion national development, social cohesion, and sustainable progress for generations to come.",
      aboutMission:
        "To empower Ugandan youth through leadership development, patriotism training, skills building, and community service — fostering unity, innovation, and active citizenship that drives national transformation.",
      mapDescription:
        "Click any district to explore membership, projects, leaders, volunteers, and events.",
      footerAbout:
        "Building Uganda Through Unity, Service, Leadership, and Development.",
    },
    stats: { ...nationalStats },
    programs: programs.map((p) => ({ ...p })),
    projects: projects.map((p) => ({ ...p })),
    events: events.map((e) => ({ ...e })),
    news: newsArticles.map((a) => ({ ...a })),
    gallery: galleryItems.map((g) => ({ ...g })),
    opportunities: opportunities.map((o) => ({ ...o })),
    resources: resources.map((r) => ({ ...r })),
    leaders: nationalLeaders.map((l) => ({ ...l })),
    partners: partners.map((p) => ({ ...p })),
    testimonials: testimonials.map((t) => ({ ...t })),
    districts: districts.map((d) => ({ ...d })),
    coreValues: coreValues.map((v, i) => ({
      id: String(i + 1),
      title: v.title,
      description: v.description,
      icon: v.icon,
    })),
    history: [
      { id: "1", year: "2020", title: "Foundation", desc: "PYU founded by youth leaders committed to national transformation." },
      { id: "2", year: "2021", title: "National Expansion", desc: "Chapters established in 50 districts with 10,000 founding members." },
      { id: "3", year: "2022", title: "Program Launch", desc: "Eleven flagship programs launched with government partnership." },
      { id: "4", year: "2023", title: "Green Uganda", desc: "Climate action campaign begins; 1 million trees planted in year one." },
      { id: "5", year: "2024", title: "Digital Transformation", desc: "PWA platform launched; digital membership and volunteer tracking." },
      { id: "6", year: "2025", title: "National Summit", desc: "Largest youth summit in Uganda; 125,000+ registered members." },
    ],
    strategicGoals: [
      { id: "1", year: "2025", title: "Mobilize 150,000 members across all districts" },
      { id: "2", year: "2026", title: "Establish fully functional chapters in every district" },
      { id: "3", year: "2027", title: "Launch regional innovation hubs in all 4 regions" },
      { id: "4", year: "2028", title: "Create 50,000 youth employment opportunities" },
      { id: "5", year: "2030", title: "Plant 10 million trees; achieve climate leadership" },
    ],
    members: [
      {
        id: "demo-member-1",
        fullName: "Amina Nakato",
        email: "member@pyu.ug",
        phone: "+256700123456",
        photoURL: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
        role: "member",
        membershipNumber: "PYU-2024-100001",
        membershipStatus: "active",
        district: "Kampala",
        volunteerHours: 48,
        badges: ["first-event", "volunteer-10", "patriot"],
        createdAt: "2024-01-15T00:00:00Z",
        updatedAt: "2024-06-01T00:00:00Z",
      },
      {
        id: "demo-admin-1",
        fullName: "David Okello",
        email: "admin@pyu.ug",
        phone: "+256700654321",
        photoURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        role: "admin",
        membershipNumber: "PYU-2023-000001",
        membershipStatus: "active",
        district: "Kampala",
        volunteerHours: 200,
        badges: ["leader", "patriot", "volunteer-100"],
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2024-06-01T00:00:00Z",
      },
      {
        id: "demo-super-1",
        fullName: "Sarah Namukasa",
        email: "superadmin@pyu.ug",
        phone: "+256700999888",
        photoURL: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200",
        role: "super_admin",
        membershipNumber: "PYU-2022-000001",
        membershipStatus: "active",
        district: "Kampala",
        volunteerHours: 500,
        badges: ["founder", "leader", "patriot"],
        createdAt: "2022-01-01T00:00:00Z",
        updatedAt: "2024-06-01T00:00:00Z",
      },
    ],
    donations: [
      {
        id: "1",
        amount: 500000,
        currency: "UGX",
        donorName: "Anonymous",
        isAnonymous: true,
        campaign: "General Fund",
        createdAt: "2025-07-20T00:00:00Z",
        status: "completed",
      },
      {
        id: "2",
        amount: 5000000,
        currency: "UGX",
        donorName: "Stanbic Bank",
        isAnonymous: false,
        campaign: "Scholarships",
        createdAt: "2025-07-15T00:00:00Z",
        status: "completed",
      },
    ],
    forumPosts: [
      {
        id: "1",
        title: "How to start a district climate club?",
        content: "Looking for guidance on launching a climate club in Wakiso. Any templates or tips?",
        author: {
          id: "1",
          name: "Faith Namukasa",
          avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
        },
        category: "Climate Action",
        likes: 24,
        replies: 8,
        createdAt: "2025-07-10T10:00:00Z",
        tags: ["climate", "district"],
      },
      {
        id: "2",
        title: "ICT Bootcamp experiences — share yours!",
        content: "Just graduated from the Nakawa digital skills bootcamp. Would love to hear from others.",
        author: { id: "2", name: "Brian Ssempijja" },
        category: "ICT",
        likes: 45,
        replies: 15,
        createdAt: "2025-07-08T14:00:00Z",
        tags: ["ict", "training"],
      },
    ],
    notifications: [],
    media: [],
    auditLogs: [
      {
        id: "1",
        user: "system",
        action: "CMS initialized with seed data",
        createdAt: new Date().toISOString(),
      },
    ],
    updatedAt: new Date().toISOString(),
  };
}
